# Generated by Django 4.0 on 2021-12-12 16:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(null=True)),
                ('media_url', models.URLField(default='https://pbs.twimg.com/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'imagetable',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.IntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'usertable',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd', models.IntegerField()),
                ('sa', models.IntegerField()),
                ('cmp', models.IntegerField()),
                ('hue', models.IntegerField()),
                ('edit', models.IntegerField()),
                ('nar', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author_id', models.ForeignKey(db_column='author_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ratingapp.user')),
                ('media_url', models.ForeignKey(db_column='media_url', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ratingapp.image')),
            ],
            options={
                'db_table': 'ratingtable',
            },
        ),
        migrations.AddField(
            model_name='image',
            name='author_id',
            field=models.ForeignKey(db_column='author_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ratingapp.user'),
        ),
    ]
