# Generated by Django 4.0 on 2021-12-19 07:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ratingapp', '0002_update_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='media_url',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='image',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ratingapp.user'),
        ),
        migrations.AddField(
            model_name='rating',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ratingapp.image'),
        ),
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ratingapp.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
