# Generated by Django 4.0 on 2021-12-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratingapp', '0003_rename_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='client',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
