# Generated by Django 4.0 on 2021-12-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratingapp', '0004_add_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='media_url',
            field=models.URLField(default='https://pbs.twimg.com/', unique=True),
        ),
    ]
