# Generated by Django 4.0 on 2022-01-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratingapp', '0005_url_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='session',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
